"""empty message

Revision ID: 7cd604b02bb5
Revises: 99d2bf932e99
Create Date: 2019-02-03 15:20:32.900579

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7cd604b02bb5'
down_revision = '99d2bf932e99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('appraise', sa.String(length=255), nullable=True))
    op.add_column('order', sa.Column('appraise_score', sa.SmallInteger(), nullable=True))
    op.add_column('order', sa.Column('appraise_status', sa.Integer(), nullable=False))
    op.add_column('order', sa.Column('create_time', sa.DATETIME(), nullable=False))
    op.add_column('order', sa.Column('nick', sa.String(length=20), nullable=True))
    op.add_column('order', sa.Column('nick_status', sa.SmallInteger(), nullable=True))
    op.add_column('order', sa.Column('pay_time', sa.DATETIME(), nullable=True))
    op.add_column('order', sa.Column('remark', sa.String(length=255), nullable=True))
    op.add_column('order', sa.Column('status', sa.SmallInteger(), nullable=False))
    op.add_column('order', sa.Column('table_id', sa.Integer(), nullable=True))
    op.add_column('order', sa.Column('update_taime', sa.DATETIME(), nullable=False))
    op.alter_column('order', 'pay_type',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order', 'pay_type',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.drop_column('order', 'update_taime')
    op.drop_column('order', 'table_id')
    op.drop_column('order', 'status')
    op.drop_column('order', 'remark')
    op.drop_column('order', 'pay_time')
    op.drop_column('order', 'nick_status')
    op.drop_column('order', 'nick')
    op.drop_column('order', 'create_time')
    op.drop_column('order', 'appraise_status')
    op.drop_column('order', 'appraise_score')
    op.drop_column('order', 'appraise')
    # ### end Alembic commands ###
