"""empty message

Revision ID: 97580d142e05
Revises: 
Create Date: 2019-02-20 13:59:49.589050

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '97580d142e05'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('apply', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='自增长id',
               autoincrement=True)
    op.alter_column('apply', 'remark',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='申请的备注',
               existing_nullable=True)
    op.alter_column('apply', 'shop_begin_time',
               existing_type=mysql.TIME(),
               comment=None,
               existing_comment='申请门店营业时间',
               existing_nullable=True)
    op.alter_column('apply', 'shop_end_time',
               existing_type=mysql.TIME(),
               comment=None,
               existing_comment='申请门店结束时间',
               existing_nullable=True)
    op.alter_column('apply', 'shop_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='申请店面id',
               existing_nullable=False)
    op.alter_column('apply', 'shop_img',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='申请门店图片',
               existing_nullable=True)
    op.alter_column('apply', 'shop_name',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='申请门店名称',
               existing_nullable=False)
    op.alter_column('apply', 'shop_prove',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='申请门店资格(营业执照图片)',
               existing_nullable=True)
    op.alter_column('apply', 'shop_tag',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='申请门店类型',
               existing_nullable=True)
    op.alter_column('apply', 'status',
               existing_type=mysql.INTEGER(display_width=1),
               comment=None,
               existing_comment='申请状态',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.drop_index('apply_shop_id', table_name='apply')
    op.drop_table_comment(
        'apply',
        existing_comment='申请门店的信息表',
        schema=None
    )
    op.alter_column('area', 'area_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='二级地区id',
               autoincrement=True)
    op.alter_column('area', 'area_name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False,
               comment=None,
               existing_comment='二级地区名称')
    op.alter_column('area', 'area_pid',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               comment=None,
               existing_comment='父地区id')
    op.drop_table_comment(
        'area',
        existing_comment='地区表',
        schema=None
    )
    op.alter_column('category_goods', 'category_name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('category_goods', 'shop_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('goods_info', 'goods_image',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False,
               comment=None,
               existing_comment='商品图片')
    op.alter_column('goods_info', 'goods_name',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='商品名称',
               existing_nullable=False)
    op.alter_column('goods_info', 'goods_notes',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='商品备注；也就是商品简介',
               existing_nullable=True)
    op.alter_column('goods_info', 'goods_price',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               comment=None,
               existing_comment='商品单价',
               existing_nullable=False)
    op.alter_column('goods_info', 'goods_status',
               existing_type=mysql.INTEGER(display_width=1, unsigned=True),
               comment=None,
               existing_comment='商品状态（默认为1：开启，0：未开启）',
               existing_nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('goods_info', 'goods_type',
               existing_type=mysql.INTEGER(display_width=255),
               comment=None,
               existing_comment='商品分类',
               existing_nullable=False)
    op.alter_column('goods_info', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='商品id',
               autoincrement=True)
    op.drop_table_comment(
        'goods_info',
        existing_comment='商品信息表\r\n',
        schema=None
    )
    op.alter_column('goods_type', 'shop_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='门店id',
               existing_nullable=True)
    op.alter_column('goods_type', 'type_name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False,
               comment=None,
               existing_comment='商品种类')
    op.drop_constraint('type_shop_id', 'goods_type', type_='foreignkey')
    op.drop_table_comment(
        'goods_type',
        existing_comment='商品种类表 关联了门店id\r\n',
        schema=None
    )
    op.add_column('merchant', sa.Column('merchant_pwd', sa.String(length=255), nullable=False))
    op.alter_column('merchant', 'merchant_name',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='商家账号的用户名',
               existing_nullable=False)
    op.alter_column('merchant', 'merchant_phone',
               existing_type=mysql.CHAR(length=11),
               comment=None,
               existing_comment='商家账号的手机号（非必填）',
               existing_nullable=True)
    op.alter_column('merchant', 'merchant_status',
               existing_type=mysql.INTEGER(display_width=2),
               comment=None,
               existing_comment='商家版状态（0：商家主账号，1：子帐号，2：不开启)',
               existing_server_default=sa.text("'0'"))
    op.drop_table_comment(
        'merchant',
        existing_comment='商家账号信息',
        schema=None
    )
    op.drop_column('merchant', 'merchant_passwd')
    op.alter_column('merchant_shop', 'merchant_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='商家账号id',
               autoincrement=True)
    op.alter_column('merchant_shop', 'remake_name',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='备注门店名',
               existing_nullable=True)
    op.alter_column('merchant_shop', 'shop_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='门店id',
               existing_nullable=False)
    op.drop_constraint('id', 'merchant_shop', type_='foreignkey')
    op.drop_constraint('shops_id', 'merchant_shop', type_='foreignkey')
    op.drop_table_comment(
        'merchant_shop',
        existing_comment='门店信息和商户信息关联的表',
        schema=None
    )
    op.add_column('order', sa.Column('update_taime', sa.DATETIME(), nullable=False))
    op.alter_column('order', 'appraise',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='买家评价内容',
               existing_nullable=True)
    op.alter_column('order', 'appraise_score',
               existing_type=mysql.INTEGER(display_width=2),
               comment=None,
               existing_comment='评分数值；',
               existing_nullable=True)
    op.alter_column('order', 'appraise_status',
               existing_type=mysql.INTEGER(display_width=2, unsigned=True),
               comment=None,
               existing_comment='评价状态；0：未评价，1：已评价，2：删除评价',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('order', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='自增长')
    op.alter_column('order', 'nick',
               existing_type=mysql.CHAR(length=20),
               comment=None,
               existing_comment='买家昵称（不得超过20个字符',
               existing_nullable=True)
    op.alter_column('order', 'nick_status',
               existing_type=mysql.INTEGER(display_width=2, unsigned=True),
               comment=None,
               existing_comment='买家昵称是否匿名； 0：不匿名，1：匿名；默认为0',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('order', 'order_id',
               existing_type=mysql.CHAR(length=20),
               comment=None,
               existing_comment='订单id；格式：年月日(8)+商家id(4)+时分秒(6)+订单号(2)')
    op.alter_column('order', 'pay_money',
               existing_type=mysql.FLOAT(precision=9, scale=2, unsigned=True),
               comment=None,
               existing_comment='支付金额',
               existing_nullable=False)
    op.alter_column('order', 'pay_time',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='付款时间',
               existing_nullable=True)
    op.alter_column('order', 'pay_type',
               existing_type=mysql.INTEGER(display_width=2, unsigned=True),
               comment=None,
               existing_comment='支付类型：0，现金，1：在线支付',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('order', 'remark',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='订单备注',
               existing_nullable=True)
    op.alter_column('order', 'shop_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='门店id',
               existing_nullable=False)
    op.alter_column('order', 'status',
               existing_type=mysql.INTEGER(display_width=2, unsigned=True, zerofill=True),
               comment=None,
               existing_comment='订单交易状态：默认为（0）；0：未付款，1：已付款，交易成功，2：交易失败，3：退款，4：删除订单',
               existing_nullable=False,
               existing_server_default=sa.text("'00'"))
    op.alter_column('order', 'table_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='桌号：默认为null； \\r\\n0：堂食；其他号码：桌号',
               existing_nullable=True)
    op.alter_column('order', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='用户id',
               existing_nullable=False)
    op.drop_index('order_id', table_name='order')
    op.drop_constraint('order_user_id', 'order', type_='foreignkey')
    op.drop_constraint('order_shop_id', 'order', type_='foreignkey')
    op.drop_table_comment(
        'order',
        existing_comment='订单信息表',
        schema=None
    )
    op.drop_column('order', 'update_time')
    op.drop_column('order', 'shop_status')
    op.alter_column('order_details', 'count_money',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='总价',
               existing_nullable=True)
    op.alter_column('order_details', 'goods_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               comment=None,
               existing_comment='商品id')
    op.alter_column('order_details', 'goods_name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False,
               comment=None,
               existing_comment='商品名称')
    op.alter_column('order_details', 'image_url',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False,
               comment=None,
               existing_comment='图片的url地址')
    op.alter_column('order_details', 'num',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='商品数量',
               existing_nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('order_details', 'order_id',
               existing_type=mysql.CHAR(length=20),
               nullable=False,
               comment=None,
               existing_comment='订单id')
    op.alter_column('order_details', 'price',
               existing_type=mysql.DOUBLE(precision=10, scale=2, asdecimal=True),
               nullable=False,
               comment=None,
               existing_comment='单价')
    op.drop_index('details_goods_id', table_name='order_details')
    op.drop_table_comment(
        'order_details',
        existing_comment='订单详情表，订单的详情主要就是购买商品的信息，通过订单的id来实现关联',
        schema=None
    )
    op.alter_column('shop_info', 'area',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               comment=None,
               existing_comment='所属地区')
    op.alter_column('shop_info', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='门店id',
               autoincrement=True)
    op.alter_column('shop_info', 'shop_begin_time',
               existing_type=mysql.TIME(),
               comment=None,
               existing_comment='门店营业开始时间',
               existing_nullable=True)
    op.alter_column('shop_info', 'shop_end_time',
               existing_type=mysql.TIME(),
               comment=None,
               existing_comment='门店营业结束时间',
               existing_nullable=True)
    op.alter_column('shop_info', 'shop_img',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='门店图片',
               existing_nullable=True)
    op.alter_column('shop_info', 'shop_intro',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='门店简介',
               existing_nullable=True)
    op.alter_column('shop_info', 'shop_name',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='门店名称',
               existing_nullable=False)
    op.alter_column('shop_info', 'shop_phone',
               existing_type=mysql.CHAR(length=11),
               comment=None,
               existing_comment='门店电话：默认为11位手机号，可以为空',
               existing_nullable=True)
    op.alter_column('shop_info', 'shop_status',
               existing_type=mysql.INTEGER(display_width=2, unsigned=True),
               comment=None,
               existing_comment='门店状态（0：未注册，1：正常运行，2：审核中，3：未营业，4：商家已删除，不存在）',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('shop_info', 'shop_tag',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='门店标签；多个标签的话，以分号隔开',
               existing_nullable=True)
    op.drop_constraint('shop_area_id', 'shop_info', type_='foreignkey')
    op.drop_table_comment(
        'shop_info',
        existing_comment='门店信息表',
        schema=None
    )
    op.alter_column('type', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='类型id',
               autoincrement=True)
    op.alter_column('type', 'type_name',
               existing_type=mysql.CHAR(length=10),
               nullable=False,
               comment=None,
               existing_comment='类型名称')
    op.drop_index('id', table_name='type')
    op.drop_table_comment(
        'type',
        existing_comment='类型表；\r\n用来区分门店的类型\r\n例如：中餐，西餐，汉堡，披萨，炸鸡',
        schema=None
    )
    op.add_column('type_shop', sa.Column('id', sa.Integer(), nullable=False))
    op.alter_column('type_shop', 'shop_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.drop_constraint('ts_shop_id', 'type_shop', type_='foreignkey')
    op.drop_constraint('ts_type_id', 'type_shop', type_='foreignkey')
    op.drop_table_comment(
        'type_shop',
        existing_comment='类型和门店关联的表；\r\n门店可以属于多个类型；\r\n例如：汉堡王，可以是汉堡，也可以是西餐',
        schema=None
    )
    op.add_column('user_info', sa.Column('id', sa.Integer(), nullable=False))
    op.alter_column('user_info', 'create_time',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=True)
    op.alter_column('user_info', 'image',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='用户头像',
               existing_nullable=True)
    op.alter_column('user_info', 'nick',
               existing_type=mysql.CHAR(length=20),
               comment=None,
               existing_comment='用户昵称(不得超过20个字符)',
               existing_nullable=True)
    op.alter_column('user_info', 'password',
               existing_type=mysql.CHAR(length=40),
               comment=None,
               existing_comment='用户密码；用哈希值存入',
               existing_nullable=False)
    op.alter_column('user_info', 'phone',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='用户手机号',
               existing_nullable=True)
    op.alter_column('user_info', 'sex',
               existing_type=mysql.ENUM('M', 'F'),
               comment=None,
               existing_comment="用户性别('M':男,默认,'F',女)",
               existing_nullable=True,
               existing_server_default=sa.text("'M'"))
    op.alter_column('user_info', 'user_area',
               existing_type=mysql.INTEGER(display_width=255),
               nullable=False,
               comment=None,
               existing_comment='用户所在地id')
    op.alter_column('user_info', 'user_name',
               existing_type=mysql.CHAR(length=11),
               comment=None,
               existing_comment='用户账号；默认用手机号，不得超过11位长度.并且不可重复')
    op.drop_index('id', table_name='user_info')
    op.drop_index('username', table_name='user_info')
    op.drop_constraint('user_area_id', 'user_info', type_='foreignkey')
    op.drop_table_comment(
        'user_info',
        existing_comment='用户信息表\r\n',
        schema=None
    )
    op.drop_column('user_info', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_info', sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False, comment='用户id'))
    op.create_table_comment(
        'user_info',
        '用户信息表\r\n',
        existing_comment=None,
        schema=None
    )
    op.create_foreign_key('user_area_id', 'user_info', 'area', ['user_area'], ['area_id'])
    op.create_index('username', 'user_info', ['user_name'], unique=True)
    op.create_index('id', 'user_info', ['user_id'], unique=True)
    op.alter_column('user_info', 'user_name',
               existing_type=mysql.CHAR(length=11),
               comment='用户账号；默认用手机号，不得超过11位长度.并且不可重复')
    op.alter_column('user_info', 'user_area',
               existing_type=mysql.INTEGER(display_width=255),
               nullable=True,
               comment='用户所在地id')
    op.alter_column('user_info', 'sex',
               existing_type=mysql.ENUM('M', 'F'),
               comment="用户性别('M':男,默认,'F',女)",
               existing_nullable=True,
               existing_server_default=sa.text("'M'"))
    op.alter_column('user_info', 'phone',
               existing_type=mysql.VARCHAR(length=255),
               comment='用户手机号',
               existing_nullable=True)
    op.alter_column('user_info', 'password',
               existing_type=mysql.CHAR(length=40),
               comment='用户密码；用哈希值存入',
               existing_nullable=False)
    op.alter_column('user_info', 'nick',
               existing_type=mysql.CHAR(length=20),
               comment='用户昵称(不得超过20个字符)',
               existing_nullable=True)
    op.alter_column('user_info', 'image',
               existing_type=mysql.VARCHAR(length=255),
               comment='用户头像',
               existing_nullable=True)
    op.alter_column('user_info', 'create_time',
               existing_type=mysql.DATETIME(),
               comment='创建时间',
               existing_nullable=True)
    op.drop_column('user_info', 'id')
    op.create_table_comment(
        'type_shop',
        '类型和门店关联的表；\r\n门店可以属于多个类型；\r\n例如：汉堡王，可以是汉堡，也可以是西餐',
        existing_comment=None,
        schema=None
    )
    op.create_foreign_key('ts_type_id', 'type_shop', 'type', ['type_id'], ['id'])
    op.create_foreign_key('ts_shop_id', 'type_shop', 'shop_info', ['shop_id'], ['id'])
    op.alter_column('type_shop', 'shop_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.drop_column('type_shop', 'id')
    op.create_table_comment(
        'type',
        '类型表；\r\n用来区分门店的类型\r\n例如：中餐，西餐，汉堡，披萨，炸鸡',
        existing_comment=None,
        schema=None
    )
    op.create_index('id', 'type', ['id'], unique=True)
    op.alter_column('type', 'type_name',
               existing_type=mysql.CHAR(length=10),
               nullable=True,
               comment='类型名称')
    op.alter_column('type', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='类型id',
               autoincrement=True)
    op.create_table_comment(
        'shop_info',
        '门店信息表',
        existing_comment=None,
        schema=None
    )
    op.create_foreign_key('shop_area_id', 'shop_info', 'area', ['area'], ['area_id'])
    op.alter_column('shop_info', 'shop_tag',
               existing_type=mysql.VARCHAR(length=255),
               comment='门店标签；多个标签的话，以分号隔开',
               existing_nullable=True)
    op.alter_column('shop_info', 'shop_status',
               existing_type=mysql.INTEGER(display_width=2, unsigned=True),
               comment='门店状态（0：未注册，1：正常运行，2：审核中，3：未营业，4：商家已删除，不存在）',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('shop_info', 'shop_phone',
               existing_type=mysql.CHAR(length=11),
               comment='门店电话：默认为11位手机号，可以为空',
               existing_nullable=True)
    op.alter_column('shop_info', 'shop_name',
               existing_type=mysql.VARCHAR(length=255),
               comment='门店名称',
               existing_nullable=False)
    op.alter_column('shop_info', 'shop_intro',
               existing_type=mysql.VARCHAR(length=255),
               comment='门店简介',
               existing_nullable=True)
    op.alter_column('shop_info', 'shop_img',
               existing_type=mysql.VARCHAR(length=255),
               comment='门店图片',
               existing_nullable=True)
    op.alter_column('shop_info', 'shop_end_time',
               existing_type=mysql.TIME(),
               comment='门店营业结束时间',
               existing_nullable=True)
    op.alter_column('shop_info', 'shop_begin_time',
               existing_type=mysql.TIME(),
               comment='门店营业开始时间',
               existing_nullable=True)
    op.alter_column('shop_info', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='门店id',
               autoincrement=True)
    op.alter_column('shop_info', 'area',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               comment='所属地区')
    op.create_table_comment(
        'order_details',
        '订单详情表，订单的详情主要就是购买商品的信息，通过订单的id来实现关联',
        existing_comment=None,
        schema=None
    )
    op.create_index('details_goods_id', 'order_details', ['goods_id'], unique=False)
    op.alter_column('order_details', 'price',
               existing_type=mysql.DOUBLE(precision=10, scale=2, asdecimal=True),
               nullable=True,
               comment='单价')
    op.alter_column('order_details', 'order_id',
               existing_type=mysql.CHAR(length=20),
               nullable=True,
               comment='订单id')
    op.alter_column('order_details', 'num',
               existing_type=mysql.INTEGER(display_width=11),
               comment='商品数量',
               existing_nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('order_details', 'image_url',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True,
               comment='图片的url地址')
    op.alter_column('order_details', 'goods_name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True,
               comment='商品名称')
    op.alter_column('order_details', 'goods_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               comment='商品id')
    op.alter_column('order_details', 'count_money',
               existing_type=mysql.VARCHAR(length=255),
               comment='总价',
               existing_nullable=True)
    op.add_column('order', sa.Column('shop_status', mysql.INTEGER(display_width=2, unsigned=True), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='商家订单删除状态：0：未删除，1：删除；默认为0；'))
    op.add_column('order', sa.Column('update_time', mysql.DATETIME(), nullable=False))
    op.create_table_comment(
        'order',
        '订单信息表',
        existing_comment=None,
        schema=None
    )
    op.create_foreign_key('order_shop_id', 'order', 'shop_info', ['shop_id'], ['id'])
    op.create_foreign_key('order_user_id', 'order', 'user_info', ['user_id'], ['user_id'])
    op.create_index('order_id', 'order', ['order_id'], unique=True)
    op.alter_column('order', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='用户id',
               existing_nullable=False)
    op.alter_column('order', 'table_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='桌号：默认为null； \\r\\n0：堂食；其他号码：桌号',
               existing_nullable=True)
    op.alter_column('order', 'status',
               existing_type=mysql.INTEGER(display_width=2, unsigned=True, zerofill=True),
               comment='订单交易状态：默认为（0）；0：未付款，1：已付款，交易成功，2：交易失败，3：退款，4：删除订单',
               existing_nullable=False,
               existing_server_default=sa.text("'00'"))
    op.alter_column('order', 'shop_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='门店id',
               existing_nullable=False)
    op.alter_column('order', 'remark',
               existing_type=mysql.VARCHAR(length=255),
               comment='订单备注',
               existing_nullable=True)
    op.alter_column('order', 'pay_type',
               existing_type=mysql.INTEGER(display_width=2, unsigned=True),
               comment='支付类型：0，现金，1：在线支付',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('order', 'pay_time',
               existing_type=mysql.DATETIME(),
               comment='付款时间',
               existing_nullable=True)
    op.alter_column('order', 'pay_money',
               existing_type=mysql.FLOAT(precision=9, scale=2, unsigned=True),
               comment='支付金额',
               existing_nullable=False)
    op.alter_column('order', 'order_id',
               existing_type=mysql.CHAR(length=20),
               comment='订单id；格式：年月日(8)+商家id(4)+时分秒(6)+订单号(2)')
    op.alter_column('order', 'nick_status',
               existing_type=mysql.INTEGER(display_width=2, unsigned=True),
               comment='买家昵称是否匿名； 0：不匿名，1：匿名；默认为0',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('order', 'nick',
               existing_type=mysql.CHAR(length=20),
               comment='买家昵称（不得超过20个字符',
               existing_nullable=True)
    op.alter_column('order', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='自增长')
    op.alter_column('order', 'appraise_status',
               existing_type=mysql.INTEGER(display_width=2, unsigned=True),
               comment='评价状态；0：未评价，1：已评价，2：删除评价',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('order', 'appraise_score',
               existing_type=mysql.INTEGER(display_width=2),
               comment='评分数值；',
               existing_nullable=True)
    op.alter_column('order', 'appraise',
               existing_type=mysql.VARCHAR(length=255),
               comment='买家评价内容',
               existing_nullable=True)
    op.drop_column('order', 'update_taime')
    op.create_table_comment(
        'merchant_shop',
        '门店信息和商户信息关联的表',
        existing_comment=None,
        schema=None
    )
    op.create_foreign_key('shops_id', 'merchant_shop', 'shop_info', ['shop_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key('id', 'merchant_shop', 'merchant', ['merchant_id'], ['merchant_id'], onupdate='CASCADE', ondelete='CASCADE')
    op.alter_column('merchant_shop', 'shop_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='门店id',
               existing_nullable=False)
    op.alter_column('merchant_shop', 'remake_name',
               existing_type=mysql.VARCHAR(length=255),
               comment='备注门店名',
               existing_nullable=True)
    op.alter_column('merchant_shop', 'merchant_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='商家账号id',
               autoincrement=True)
    op.add_column('merchant', sa.Column('merchant_passwd', mysql.VARCHAR(length=255), nullable=False, comment='商家账号的密码'))
    op.create_table_comment(
        'merchant',
        '商家账号信息',
        existing_comment=None,
        schema=None
    )
    op.alter_column('merchant', 'merchant_status',
               existing_type=mysql.INTEGER(display_width=2),
               comment='商家版状态（0：商家主账号，1：子帐号，2：不开启)',
               existing_server_default=sa.text("'0'"))
    op.alter_column('merchant', 'merchant_phone',
               existing_type=mysql.CHAR(length=11),
               comment='商家账号的手机号（非必填）',
               existing_nullable=True)
    op.alter_column('merchant', 'merchant_name',
               existing_type=mysql.VARCHAR(length=255),
               comment='商家账号的用户名',
               existing_nullable=False)
    op.drop_column('merchant', 'merchant_pwd')
    op.create_table_comment(
        'goods_type',
        '商品种类表 关联了门店id\r\n',
        existing_comment=None,
        schema=None
    )
    op.create_foreign_key('type_shop_id', 'goods_type', 'shop_info', ['shop_id'], ['id'])
    op.alter_column('goods_type', 'type_name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True,
               comment='商品种类')
    op.alter_column('goods_type', 'shop_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='门店id',
               existing_nullable=True)
    op.create_table_comment(
        'goods_info',
        '商品信息表\r\n',
        existing_comment=None,
        schema=None
    )
    op.alter_column('goods_info', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='商品id',
               autoincrement=True)
    op.alter_column('goods_info', 'goods_type',
               existing_type=mysql.INTEGER(display_width=255),
               comment='商品分类',
               existing_nullable=False)
    op.alter_column('goods_info', 'goods_status',
               existing_type=mysql.INTEGER(display_width=1, unsigned=True),
               comment='商品状态（默认为1：开启，0：未开启）',
               existing_nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('goods_info', 'goods_price',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               comment='商品单价',
               existing_nullable=False)
    op.alter_column('goods_info', 'goods_notes',
               existing_type=mysql.VARCHAR(length=255),
               comment='商品备注；也就是商品简介',
               existing_nullable=True)
    op.alter_column('goods_info', 'goods_name',
               existing_type=mysql.VARCHAR(length=255),
               comment='商品名称',
               existing_nullable=False)
    op.alter_column('goods_info', 'goods_image',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True,
               comment='商品图片')
    op.alter_column('category_goods', 'shop_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('category_goods', 'category_name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.create_table_comment(
        'area',
        '地区表',
        existing_comment=None,
        schema=None
    )
    op.alter_column('area', 'area_pid',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               comment='父地区id')
    op.alter_column('area', 'area_name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True,
               comment='二级地区名称')
    op.alter_column('area', 'area_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='二级地区id',
               autoincrement=True)
    op.create_table_comment(
        'apply',
        '申请门店的信息表',
        existing_comment=None,
        schema=None
    )
    op.create_index('apply_shop_id', 'apply', ['shop_id'], unique=False)
    op.alter_column('apply', 'status',
               existing_type=mysql.INTEGER(display_width=1),
               comment='申请状态',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('apply', 'shop_tag',
               existing_type=mysql.VARCHAR(length=255),
               comment='申请门店类型',
               existing_nullable=True)
    op.alter_column('apply', 'shop_prove',
               existing_type=mysql.VARCHAR(length=255),
               comment='申请门店资格(营业执照图片)',
               existing_nullable=True)
    op.alter_column('apply', 'shop_name',
               existing_type=mysql.VARCHAR(length=255),
               comment='申请门店名称',
               existing_nullable=False)
    op.alter_column('apply', 'shop_img',
               existing_type=mysql.VARCHAR(length=255),
               comment='申请门店图片',
               existing_nullable=True)
    op.alter_column('apply', 'shop_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='申请店面id',
               existing_nullable=False)
    op.alter_column('apply', 'shop_end_time',
               existing_type=mysql.TIME(),
               comment='申请门店结束时间',
               existing_nullable=True)
    op.alter_column('apply', 'shop_begin_time',
               existing_type=mysql.TIME(),
               comment='申请门店营业时间',
               existing_nullable=True)
    op.alter_column('apply', 'remark',
               existing_type=mysql.VARCHAR(length=255),
               comment='申请的备注',
               existing_nullable=True)
    op.alter_column('apply', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='自增长id',
               autoincrement=True)
    # ### end Alembic commands ###
